language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - sudo apt-get -qq update
  - sudo apt-get install unzip
  - sudo apt-get install exiftool
  - wget http://kakadusoftware.com/wp-content/uploads/2014/06/KDU7A2_Demo_Apps_for_Ubuntu-x86-64_170827.zip
  - unzip KDU7A2_Demo_Apps_for_Ubuntu-x86-64_170827.zip
  - sudo mv KDU7A2_Demo_Apps_for_Ubuntu-x86-64_170827 /opt/kakadu
  - pip install -r requirements.txt
script:
  - py.test